% This is the main function of EP21 ADAS HiL report m file
% with little change, this can also be used on other conditions
% for autonomous report generation

%cd('C:\Users\CaoXing\Desktop\ReportLatex');
%%% This gives the Path where the .m file is stored

fname=mfilename();% m funtion name
completepath=mfilename('fullpath');% fullpath of mfile with mfilename
mpath=completepath(1:end-numel(fname));% fullpath of mfile without mfilename

doktitle='EP21 ADAS Test Report';
dokauthor='Caoxing';

%% the idea is: new a .tex file, then add LaTex Commands to it
% first new a .tex file
texfile=strcat(mpath,'\EP21_ADAS_Test_Report.tex');
%%%%%%%%%%%%%  HEADER
glossaryentries='';
% glossaryentries={...
%                 '% Glossary Entries'
%                 '\newglossaryentry{potato}{name={potato},plural={potatoes},';...
%                 'description={starchy tuber}}';...
%                 '\newglossaryentry{cabbage}{name={cabbage},';...
%                 'description={vegetable with thick green or purple leaves}}';...
%                 '\newglossaryentry{turnip}{name={turnip},';...
%                 'description={round pale root vegetable}}';...
%                 '\newglossaryentry{carrot}{name={carrot},';...
%                 'description={orange root}}';...
%                 '% and Acronyms'
%                 '\newacronym{MS}{MS}{Microsoft}';...
%                 '\newacronym{CD}{CD}{Compact Disc}';...
%                 '\newacronym{PC}{PC}{Personal Computer}';...
%                 };
% in the subfunction below to set the paper setup
R2L_writeheader(texfile,doktitle,dokauthor,glossaryentries)

%%%%%%%%%
R2L_Append2TexOutput(texfile,{...   %Result List label 9999                         
                            '\centerline{\Large{\textbf{Result List}}}';...
                            '\begin{CJK}{GBK}{kai}';...
                            '\begin{tabbing}';...
                            '\hspace*{30bp}\=blank\hspace*{30bp}\=testcasename\hspace*{200bp} \=result\kill';})
%% Read Data From Excel

%% write all Testrusults
resultFilePath=strcat(mpath,'Data\');
resultFileName='TestResult.xlsx';
[~,~,resultDatacell]=xlsread(strcat(resultFilePath,resultFileName));
for i=1:length(resultDatacell)
    if(strcmpi(resultDatacell{i,2},'pass'))%if testresult pass, no sensitive to Caps
        R2L_Append2TexOutput(texfile,{...
        strcat([ ],'\>\textit{\underline{\ref{w',num2str(i),'}}} \>',resultDatacell{i,1},  '\>',resultDatacell{i,2},'\\')});
    else if(strcmpi(resultDatacell{i,2},'fail'))%if testresult pass, no sensitive to Caps
        R2L_Append2TexOutput(texfile,{...
        strcat([ ],'\>\textit{\underline{\ref{w',num2str(i),'}}} \>',resultDatacell{i,1},  '\>\textcolor[rgb]{1,0,0}{',resultDatacell{i,2},'}\\')});
        else
            R2L_Append2TexOutput(texfile,{...
            strcat([ ],'\>\textit{\underline{\ref{w',num2str(i),'}}} \>',resultDatacell{i,1},  '\>\textcolor[rgb]{1,1,0}{',resultDatacell{i,2},'}\\')});
        end
    end
end
% remmenber endding tabbing
R2L_Append2TexOutput(texfile,{'\end{tabbing}'});
R2L_Append2TexOutput(texfile,{'\end{CJK}'});
%% This is for the while loop to display the TestResult
for i=1:length(resultDatacell)
    R2L_Append2TexOutput(texfile,{'\newpage'});
    R2L_Append2TexOutput(texfile,{strcat('\section{',resultDatacell{i,1},'}')});
    % add text
    R2L_Append2TexOutput(texfile,{'\begin{CJK}{GBK}{kai}';...
                            '\begin{tabbing}';...
                            '\hspace*{40bp}\=blank\hspace*{80bp}\=Contents\kill';...
                            strcat(32,'\>TestcaseName:\>',resultDatacell{i,1},'\\');...
                            strcat(32,'\>Result:\>',resultDatacell{i,2},'\\');...
                            strcat(32,'\>Vehicle:\>','EP21 2018','\\');...
                            strcat(32,'\>Engineer:\>','Author','\\');...
                            strcat(32,'\>Date:\>',date,'\\');...
                            '\end{tabbing}';...
                            '\end{CJK}';...
                            });%add text
    %%plot figure and save them in temp file
    %get data from .csv file
    csvFileName=resultDatacell{i,1};
    csvFileFullPath=strcat(resultFilePath,csvFileName,'.csv');
    data=csvread(csvFileFullPath,1,0);
    [row,col]=size(data);
    fid=fopen(csvFileFullPath);
    csvtitle = textscan(fid, '%s',col,'delimiter', ',');
    fclose(fid);
    csvstructdata=struct();
    for j=1:col
        csvstructdata=setfield(csvstructdata,char(csvtitle{1}(j)),data(:,j));
    end
%%
        x=csvstructdata.T_Stamp;
        Vx=csvstructdata.Vx;
        SetSpd=csvstructdata.SetSpd;
        OnSw=csvstructdata.OnSw;
        SetSw=csvstructdata.SetSw;
        SpdDecSw=csvstructdata.SpdDecSw;
        SpdIncSw=csvstructdata.SpdIncSw;
        ACCSysSt=csvstructdata.ACCSysSt;
        Ax=csvstructdata.Ax;
        ACCReqVa=csvstructdata.ACCReqVa;
        hplo=figure(10000+4*i-3);
        plot(x,Vx,x,SetSpd,'linewidth',2);
        xlabel('Time/s');
        ylabel('V/(km/h)');
        legend('Vx','SetSpd');
        grid on;
        set(hplo,'Position',[200 100 800 300])
        set(hplo,'PaperSize',[9 7])
        set(hplo,'PaperPosition',[-0.5 0.5 10 7])
        title('Vehicle Speed');
        print(strcat('fig',num2str(10000+4*i-3)),'-depsc');
        close(figure(10000+4*i-3));
        
        hplo=figure(10000+4*i-2);
        plot(x,OnSw,x,SetSw,x,ACCSysSt,x,SpdIncSw,x,SpdDecSw,'linewidth',2);
        xlabel('Time/s');
        ylabel('Control Signals');
        legend('OnSw','SetSw','ACCSysSt','SpdIncSw','SpdDecSw');
        grid on;
        set(hplo,'Position',[200 100 800 300])
        set(hplo,'PaperSize',[9 7])
        set(hplo,'PaperPosition',[-0.5 0.5 10 7])
        title('ACC Control Input');
        print(strcat('fig',num2str(10000+4*i-2)),'-depsc');
        close(figure(10000+4*i-2));
        
        hplo=figure(10000+4*i-1);
        plot(x,Ax,x, ACCReqVa,'linewidth',2);
        xlabel('Time/s');
        ylabel('g');
        legend('Ax',' ACCReqVa');
        grid on;
        set(hplo,'Position',[200 100 800 300])
        set(hplo,'PaperSize',[9 7])
        set(hplo,'PaperPosition',[-0.5 0.5 10 7])
        title('Vehicle Ax ');
        print(strcat('fig',num2str(10000+4*i-1)),'-depsc');
        close(figure(10000+4*i-1));
        
        hplo=figure(10000+4*i);
        plot(x,Vx,x,SetSpd,'linewidth',2);
        xlabel('Time/s');
        ylabel('V/(km/h)');
        legend('Vx','SetSpd');
        grid on;
        set(hplo,'Position',[200 100 800 300])
        set(hplo,'PaperSize',[9 7])
        set(hplo,'PaperPosition',[-0.5 0.5 10 7])
        title('Vehicle Speed');
        print(strcat('fig',num2str(10000+4*i)),'-depsc');
        close(figure(10000+4*i));

%%        
    newcell={...
    strcat('\label{w',num2str(i),'}');...
    '\begin{figure}[h!] ';...
    '\centering ';...
    '\subfigure{';...
    '\begin{minipage}[t]{0.4\linewidth}';...
    '%\centering';...
    strcat('\includegraphics[width=2in]{fig',num2str(10000+4*i-3),'.eps}');...
    '\end{minipage}';...
    '}';...
    '\subfigure{';...
    '\begin{minipage}[t]{0.4\linewidth}';...
    '%\centering';...
    strcat('\includegraphics[width=2in]{fig',num2str(10000+4*i-2),'.eps}');...
    '\end{minipage}';...
    '}';...
    '';...
    '\subfigure{';...
    '\begin{minipage}[t]{0.4\linewidth}';...
    '%\centering';...
    strcat('\includegraphics[width=2in]{fig',num2str(10000+4*i-2),'.eps}');...
    '\end{minipage}';...
    '}';...
    '\subfigure{';...
    '\begin{minipage}[t]{0.4\linewidth}';...
    '%\centering';...
    strcat('\includegraphics[width=2in]{fig',num2str(10000+4*i-1),'.eps}');...
    '\end{minipage}';...
    '}';...
    '\caption{TestData}';...
    '\end{figure}'...
    };
R2L_Append2TexOutput(texfile,newcell);
end


%% 
R2L_Append2TexOutput(texfile,{'\end{document}'});
